### ISSUE TITLE
non funziona

### ISSUE THREAD

**Issue by gaecola** [franjsco/iliadly#2]
Ciao,
Lodevole la tua iniziativa. Grazie.
l'ho appena installato (installazione effettuata con successo, nessun errore) e lanciato, ma purtroppo non funziona.
Ritorna "iliadly: Errore nel prelevare i dati. Assicurati di essere connesso ad internet con SIM iliad. "
(la SIM utilizzata ovviamente è ILIAD).

Potrebbe essere causato dal fatto che la pagina https://www.iliad.it/account/consumi-e-credito invocata dalla script, attualmente richiede autenticazione con le credenziali dell'utente Iliad (anche quando si utilizza la SIM Iliad)?

di seguito evidenze:
--------------------------------------------------------------------------
gaetano@OMVJ206:~$ curl ipinfo.io/ip
37.161.47.176
--------------------------------------------------------------------------
gaetano@OMVJ206:~/domoticz/iliadly$ ./iliadly.py 
iliadly: Errore nel prelevare i dati. Assicurati di essere connesso ad internet con SIM iliad. 
--------------------------------------------------------------------------
gaetano@OMVJ206:~/domoticz/iliadly$ wget https://www.iliad.it/account/consumi-e-credito.htm
--2022-05-16 10:43:59--  https://www.iliad.it/account/consumi-e-credito.htm
Risoluzione di www.iliad.it (www.iliad.it)... 83.158.240.200
Connessione a www.iliad.it (www.iliad.it)|83.158.240.200|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 302 Found
Posizione: http://www.iliad.it/account/consumi-e-credito.htm [segue]
--2022-05-16 10:43:59--  http://www.iliad.it/account/consumi-e-credito.htm
Connessione a www.iliad.it (www.iliad.it)|83.158.240.200|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: non specificato [text/html]
Salvataggio in: "consumi-e-credito.htm"

consumi-e-credito.htm             [ <=>                                           ]  13,87K  --.-KB/s    in 0,03s   

2022-05-16 10:43:59 (434 KB/s) - "consumi-e-credito.htm" salvato [14198]

gaetano@OMVJ206:~/domoticz/iliadly$ cat consumi-e-credito.htm 
<!doctype html>
<html lang="it">
<head>
   <meta charset="utf-8">

   <title>iliad - Benvenuto in iliad</title>
   
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

   
   <meta name="msapplication-tap-highlight" content="no">

   
   <link rel="manifest" href="/manifest.json">

      
   <meta name="mobile-web-app-capable" content="yes">
   <meta name="application-name" content="Iliad">
   <link rel="icon" type="image/png" sizes="192x192" href="/assets/favicon/android-icon-192x192.png">
   <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
   <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon/favicon-96x96.png">
   <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">

   
   <meta name="apple-mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-status-bar-style" content="black">
   <meta name="apple-mobile-web-app-title" content="Iliad">
   <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicon/apple-icon-57x57.png">
   <link rel="apple-touch-icon" sizes="60x60" href="/assets/favicon/apple-icon-60x60.png">
   <link rel="apple-touch-icon" sizes="72x72" href="/assets/favicon/apple-icon-72x72.png">
   <link rel="apple-touch-icon" sizes="76x76" href="/assets/favicon/apple-icon-76x76.png">
   <link rel="apple-touch-icon" sizes="114x114" href="/assets/favicon/apple-icon-114x114.png">
   <link rel="apple-touch-icon" sizes="120x120" href="/assets/favicon/apple-icon-120x120.png">
   <link rel="apple-touch-icon" sizes="144x144" href="/assets/favicon/apple-icon-144x144.png">
   <link rel="apple-touch-icon" sizes="152x152" href="/assets/favicon/apple-icon-152x152.png">
   <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-icon-180x180.png">

   
   <meta name="msapplication-TileImage" content="/assets/favicon/ms-icon-144x144.png">
   <meta name="msapplication-TileColor" content="#2F3BA2">

   
   <meta name="theme-color" content="#CC0000">

   
         <meta property='og:image' content='https://www.iliad.it/assets/images/logo_iliad.png'/>
   
         <link rel="stylesheet" href="/assets/styles/custom-bootstrap.css?v=4b0da401526903dd5795756808390b64">
   <link rel="stylesheet" href="/assets/libs/remodal/remodal.css">
   <link rel="stylesheet" href="/assets/libs/remodal/remodal-default-theme.css">
   <link rel="stylesheet" href="/assets/libs/jquery-slidebars/slidebars.min.css?v=d61283d49cf7b1301d43aa04ff96b160">
   <link rel="stylesheet" href="/assets/styles/main.css?v=05e6c9da08f0887b450ab735eb39810f">

   <script src="/assets/libs/jquery-v3.2.1/jquery.min.js?v=c9f5aeeca3ad37bf2aa006139b935f0a"></script>
   <script src="/assets/libs/jquery-slidebars/slidebars.min.js?v=c1753c151e33bcb2899033de50cd2eeb"></script>
   <script src="/assets/scripts/common.min.js?v=20f2837037cfa83272168c6a5c001c01"></script>
   <script src="/assets/libs/remodal/remodal.min.js?v=27766f7f253c55e082376b092bcf2f1e"></script>

   <script src="/assets/libs/jquery-ui/jquery-ui.js"></script>
   <link rel="stylesheet" href="/assets/libs/jquery-ui/jquery-ui.min.css?v=ec4ebe26afcae69ed461429b22179e16">
   <link rel="stylesheet" href="/assets/libs/jquery-ui/jquery-ui.theme.min.css?v=fedb1602fd53d77f216d11ecb15b782e">
   <link rel="stylesheet" href="/assets/libs/jquery-ui/jquery-ui.structure.min.css?v=880bfa2ab3cb8b3632512334b20cc99f">

   <link rel="stylesheet" href="/account/styles/externe.css?v=c41560991773b257942c23154fab0392">
   <script src="/account/scripts/account.min.js?v=795ffadcf31b4406292a3d866fc4cf23"></script>

   <script>var fm_network = 1;</script> </head>

<body id="account-autologin" class="main acc_autologin" data-theme="main">

   <div class="remodal-bg">

      <nav id="navbar" class="navbar navbar-expand-md navbar-fm navbar-light remodal-bg">
   <div id="container" class="container-fluid container-smooth">
      <div class="navbar-header">
                     <div id="nav-icon">
               <span></span>
               <span></span>
               <span></span>
            </div>
                  <a class="navbar-brand" href="//www.iliad.it">
            <img alt="iliad mobile" title="Benvenuto in iliad" src="/assets/images/logo.png">
         </a>
      </div>

               <div class="main-nav">
            <ul class="nav navbar-nav main-menu-items">
   <li>
      <a href="//www.iliad.it/offerte-iliad-mobile.html">
         <i class="i-sim"></i> Mobile
      </a>
   </li>
   <li>
      <a href="//www.iliad.it/offerte-iliad-fibra.html">
         <i class="i-item-box"></i> Fibra
      </a>
   </li>
   <li>
      <a class="" href="//www.iliad.it/account/smartphone">
         <i class="i-item-mobile"></i> Smartphone
      </a>
   </li>
   <li>
      <a class="" href="https://puntivendita.iliad.it/map/">
         <i class="i-shop"></i> Punti vendita
      </a>
   </li>
   <li>
      <a href="https://assistenza.iliad.it">
         <i class="i-support"></i> Assistenza
      </a>
   </li>
   <li>
      <a href="//www.iliad.it/perche-iliad.html">
         <i class="i-razzo"></i> Perché iliad?
      </a>
   </li>
</ul>
         </div>
      
      <div class="account">
         <ul class="buttons nav navbar-nav">
            <li class="nav-item"><a href="//www.iliad.it/account/"><i id="i-user" class="i-selfcare"></i><span class="hidden-phone"> Area Personale</span></a></li>
         </ul>
      </div>
   </div>
</nav>

      <div class="wrapper-page remodal-bg" >
         <div class="container container-smooth">
            <div class="main-nav nav-menu" role="navigation" off-canvas="main-nav left overlay">
               <ul class="nav navbar-nav main-menu-items">
   <li>
      <a href="//www.iliad.it/offerte-iliad-mobile.html">
         <i class="i-sim"></i> Mobile
      </a>
   </li>
   <li>
      <a href="//www.iliad.it/offerte-iliad-fibra.html">
         <i class="i-item-box"></i> Fibra
      </a>
   </li>
   <li>
      <a class="" href="//www.iliad.it/account/smartphone">
         <i class="i-item-mobile"></i> Smartphone
      </a>
   </li>
   <li>
      <a class="" href="https://puntivendita.iliad.it/map/">
         <i class="i-shop"></i> Punti vendita
      </a>
   </li>
   <li>
      <a href="https://assistenza.iliad.it">
         <i class="i-support"></i> Assistenza
      </a>
   </li>
   <li>
      <a href="//www.iliad.it/perche-iliad.html">
         <i class="i-razzo"></i> Perché iliad?
      </a>
   </li>
</ul>
            </div>
            <div class="main-menu-overlay"></div>

                           
<div class="flash-container"></div>            
                  <div class="page">

      <noscript>
         <p align="center">
            Avviso: JavaScript non è abilitato nel tuo browser<br>
            Potresti riscontrare problemi di funzionamento sul nostro sito.
         </p>
      </noscript>

      <h1 id="redirect-progress" style="display:none;">
         Autenticazione in corso...
      </h1>

      <h1 id="no-cookies" style="display:none;" class="red">
         Devi accettare i cookie.
      </h1>

      <script language="javascript">
         if( navigator.cookieEnabled ) {
            document.getElementById('redirect-progress').style.display = 'block';
            document.location.href = "https:\/\/www.iliad.it\/account\/consumi-e-credito.htm?autolog=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTI2OTA2MzksImV4cCI6MTY1MjY5MDY5OSwibG9naW4iOiI3MTk5OTQzMCIsIm1zaXNkbiI6IjM1MTg4NDc0MzAifQ.ImfQiNoycKj8urgCGVeu-gJZ9yMBmja1Mh0VqzfUmos";
         }
         else {
            document.getElementById('no-cookies').style.display = 'block';
         }
      </script>

   </div>
         </div>
      </div>

      <div id="footer" class="footer no-print">
   <div class="page-container">
      
      <div class="grid-l actions">
         <a href="https://puntivendita.iliad.it/map/" onclick="_paq.push(['trackEvent', 'GoToStore', 'Clic on iliad Store Button on footer', 'Store iliad Button']);">Trova il punto vendita più vicino a te</a>
         <a href="https://assistenza.iliad.it/mobile/supporto/29/" onclick="_paq.push(['trackEvent', 'Corporate', 'Clic on FAQ Link on footer', 'Corporate FAQ link']);">Domande frequenti</a>
      </div>

      <div class="socials grid-l">
         <div class="grid-c">
            <a target="_blank" href="https://www.facebook.com/IliadItalia/" class="i-facebook"></a>
         </div>
         <div class="grid-c">
            <a target="_blank" href="https://www.instagram.com/iliaditalia" class="i-instagram"></a>
         </div>
         <div class="grid-c">
            <a target="_blank" href="https://twitter.com/IliadItalia" class="i-twitter"></a>
         </div>
         <div class="grid-c">
            <a target="_blank" href="https://www.linkedin.com/company/iliaditalia/" class="i-linkedin"></a>
         </div>
         <div class="grid-c">
            <a target="_blank" href="https://www.youtube.com/channel/UCIPsMRZ9208ceXgsCJovFDA" class="i-youtube"></a>
         </div>
      </div>
      <div class="grid-l">
         <div class="grid-c cell-top w-tablet-4 w-desktop-4 menu">
            <h5>I tuoi servizi</h5>
            <ul>
               <li><a href="//www.iliad.it/account/">Area Personale</a></li>
               <li><a href="https://assistenza.iliad.it">Assistenza</a></li>
               <li><a href="//www.iliad.it/account/ricarica">Ricarica</a></li>
               <li><a href="//www.iliad.it/copertura/index.html">Verifica copertura</a></li>
               <li><a href="https://puntivendita.iliad.it/map/">iliad Store</a></li>
               <li><a href="//www.iliad.it/contact.html">Contattaci</a></li>
            </ul>
         </div>
         <div class="grid-c cell-top w-tablet-4 w-desktop-4 menu">
            <h5>Termini e condizioni</h5>
            <ul>
               <li><a href="//www.iliad.it/condizioni-generali-di-contratto.html" target="_blank">Condizioni Generali di Contratto</a></li>
               <li>
                  <a href="//www.iliad.it/sintesi-contrattuale.html" target="_blank">
                     Sintesi contrattuale
                  </a>
               </li>
               <li><a href="/docs/informativa_privacy/informativa_privacy_2022-01-14.pdf" target="_blank" content="Informativa Privacy utenti iliad" title="Informativa Privacy.">Informativa Privacy utenti iliad</a></li>
               <li><a href="//www.iliad.it/roaming.html" target="_blank">Roaming</a></li>
               <li><a href="//www.iliad.it/trasparenza-tariffaria.html" target="_blank">Trasparenza Tariffaria</a></li>
               <li><a href="//www.iliad.it/brochure-prezzi.html" target="_blank">Brochure Prezzi</a></li>
               <li>
                  <a href="/docs/blocco_sms_bancari_a_pagamento.pdf" target="_blank">
                     Tariffe SMS bancari
                  </a>
               </li>
                              <li>
                  <a href="//www.iliad.it/carta-dei-servizi.html" target="_blank">Carta dei servizi</a>
               </li>
               <li>
                  <a href="//www.iliad.it/qualita-dei-servizi.html" target="_blank">Qualità dei servizi</a>
               </li>
               <li>
                  <a href="//www.iliad.it/agevolazioni-per-non-vedenti-e-non-udenti.html" target="_blank">Agevolazioni per non vedenti e non udenti</a>
               </li>
               <li><a href="//www.iliad.it/condizioni-di-utilizzo-del-sito.html" target="_blank">Condizioni di utilizzo e privacy del sito e delle app</a></li>
               <li><a href="//www.iliad.it/modulistica.html" target="_blank">Modulistica</a></li>
               <li><a href="/cookies.html" target="_blank">Impostazioni e Cookie policy</a></li>
            </ul>
         </div>
         <div class="grid-c cell-top w-tablet-4 w-desktop-4 menu">
            <h5>iliad</h5>
            <ul>
               <li><a href="https://corporate.iliad.it/chisiamo" target="_blank">Chi siamo</a></li>
               <li><a href="https://corporate.iliad.it/media/" target="_blank">Stampa</a></li>
               <li><a href="https://corporate.iliad.it/lavorareiniliad" target="_blank">Lavora con noi</a></li>
               <li><a href="https://corporate.iliad.it/solidali/" target="_blank">Iniziative solidali</a></li>
            </ul>
         </div>
      </div>
      <div class="conciliazione">
         Accedi alla piattaforma ConciliaWeb per presentare istanze di risoluzione delle controversie. Per maggiori informazioni
         <a href="https://www.agcom.it/procedura-di-conciliazione">https://www.agcom.it/procedura-di-conciliazione</a>
      </div>
      <div class="iliad-spa">
         <span class="bold">Iliad Italia S.p.A.</span><br>
         Sede legale: Viale Francesco Restelli 1/A - 20124, Milano - Partita IVA: 13970161009 - Numero REA: MI - 2126511 - Capitale sociale: 350.000.000 €
      </div>

                     <div class="mentions-link">
         
   
            

   
          

</div>
<div id="mentions">
      
      </div>
         </div>

   
</div>

   </div>

<script type='text/javascript'>
		var _paq = window._paq = window._paq || [];
		/* tracker methods like 'setCustomDimension' should be called before 'trackPageView' */
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function() {
		var u='//stats.iliad.it/';
		_paq.push(['setTrackerUrl', u+'matomo.php']);
		_paq.push(['setSiteId', '1']);
		var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
		g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
		})();
	</script></body>
	

<script>
   $(document).ready(function () {
      Freemwork.initAccessiway()
   });
</script>
</html>

**Comment by franjsco** [comment]
Ciao  @gaecola,
grazie e perdonami il ritardo nel risponderti.

Purtroppo il progetto non è più manuntenuto in quanto non ho più iliad.

Se hai interesse puoi forkarlo.

Un saluto
